type Product implements Node{
  id: String!
  name: String!
  description: String
  subProducts: [SubProduct]
}

type SubProduct implements Node {
  id: String!
  name: String!
  image: String!
  retailPrice: Int!
}

type Cms implements Node {
  id: String!
  products: [Product]
}

type Metadata {
  publishedAt: Date
  updatedAt: Date
}
